name: Build external pull request
on:
  pull_request:
    branches:
      - master
env:
    BASE_REPO: ${{ github.event.pull_request.base.repo.clone_url }}
    PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.clone_url }}
jobs:
  maven-verify:
    if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy maven settings
        run: |
          wget https://raw.githubusercontent.com/entur/ror-maven-settings/master/.m2/settings.xml -O .github/workflows/settings.xml
      - uses: actions/setup-java@v4
        with:
          java-version: 17.0.13
          distribution: liberica
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Run maven build
        run: mvn verify -s .github/workflows/settings.xml
  